version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"    # Porta MQTT
      - "8083:8083"    # WebSocket MQTT
      - "8081:8081"    # API REST
      - "18083:18083"  # Dashboard Web
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: emqx_auth
      POSTGRES_USER: emqx_user
      POSTGRES_PASSWORD: emqx_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emqx_user -d emqx_auth"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local